web-infra-dev/midscene

packages/cli/package.json
packages/midscene/package.json
packages/visualizer-report/package.json
packages/visualizer/package.json
packages/web-integration/package.json
packages/web-integration/tests/__snapshots__/extractor.test.ts.snap
scripts/release.js

Fixed conflicts between release format and biome lint

workflow(cd): optimize release script

---

packages/midscene/src/ai-model/automation/planning.ts

Fix English prompt  word error
#58

fix(prompt): change my to may

---

packages/web-integration/package.json

update puppeteer version requirement from `^23` to `>=20`

feat(web): update peer deps version range

---

apps/site/docs/en/docs/more/faq.md
apps/site/docs/zh/docs/more/faq.md
packages/cli/src/index.ts
packages/web-integration/src/extractor/extractor.ts
packages/web-integration/tests/ai/puppeteer/utils.ts

1. fix the flashing issue in Cli
2. add some FAQ doc to explain

fix(cli): the flashing issue in cli headed mode

---

packages/midscene/src/utils.ts
packages/web-integration/README.md
packages/web-integration/package.json
packages/web-integration/src/appium/page.ts
packages/web-integration/src/common/tasks.ts
packages/web-integration/src/common/utils.ts
packages/web-integration/src/debug/index.ts
packages/web-integration/src/index.ts
packages/web-integration/src/page.ts
packages/web-integration/src/puppeteer/base-page.ts
packages/web-integration/tests/ai/native/appium/dongchedi.test.ts
packages/web-integration/tests/ai/web/playwright/tool.ts
packages/web-integration/tests/unit-test/web-extractor.test.ts

- define appium export in package.json
- fix dongchedi tests in android

define appium export in package.json & encapsulated screenshot picture path generation

---

packages/visualizer/src/component/timeline.tsx
packages/visualizer/src/index.less
packages/visualizer/src/index.tsx

1. move the case selector to the upper left corner
2. fix the timeline re-render issue

chore: adjust the report UI

---

packages/visualizer/src/component/env-config.tsx

When I tried to use it, I discovered an experience issue right at the beginning, so I fixed it by the way.

fix: tooltip of env config

---

apps/site/docs/en/model-provider.md
apps/site/docs/zh/model-provider.md
apps/site/rspress.config.ts
packages/midscene/src/ai-model/automation/index.ts
packages/midscene/src/ai-model/common.ts
packages/midscene/src/ai-model/inspect.ts
packages/midscene/src/ai-model/openai/index.ts
packages/midscene/src/ai-model/prompt/planning.ts
packages/midscene/tests/ai/evaluate/__snapshots__/planning.test.ts.snap
packages/midscene/tests/ai/evaluate/planning.test.ts
packages/midscene/tests/ai/openai.test.ts

Optimize the SDK param to support more models, like ’qwen‘ from aliyun.

feat: support more model

---

apps/site/docs/en/index.mdx
apps/site/docs/zh/index.mdx
apps/site/docs/zh/model-provider.md
packages/midscene/tests/ai/connectivity.test.ts
packages/web-integration/src/chrome-extension/USKeyboardLayout.ts
packages/web-integration/src/chrome-extension/cdpInput.ts
packages/web-integration/src/chrome-extension/page.ts

Use cdp input from puppeteer to implement the type and press event

fix: keypress issue in chrome extension

---

apps/site/docs/en/model-provider.md
apps/site/docs/zh/model-provider.md
packages/midscene/src/ai-model/openai/index.ts
packages/midscene/src/env.ts
packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts

To solve the qwen max_tokens limit: https://github.com/web-infra-dev/midscene/issues/211

feat: let max_tokens configurable

---

packages/midscene/src/action/executor.ts
packages/visualizer/modern.config.ts
packages/visualizer/src/extension/scripts/stop-water-flow.ts
packages/visualizer/src/extension/scripts/water-flow.ts
packages/visualizer/unpacked-extension/manifest.json
packages/web-integration/src/chrome-extension/dynamic-scripts.ts
packages/web-integration/src/chrome-extension/page.ts

feat(chrome-devtool): water flow animation on the target page

---

apps/site/docs/en/index.mdx

Previously, the wording felt slightly awkward, so in this PR, I’ve made some adjustments to improve clarity and flow while retaining the original meaning.

docs: update wording in index.mdx

---

packages/midscene/src/ai-model/prompt/llm-planning.ts
packages/midscene/tests/ai/evaluate/plan/planning.test.ts

fix(prompt): resolve params format error

---

packages/midscene/modern.config.ts
packages/midscene/src/ai-model/ui-tars-planning.ts
packages/midscene/tests/ai/evaluate/ai-data/assertion/online_order.json
packages/midscene/tsconfig.json
packages/visualizer/modern.config.ts
packages/visualizer/tsconfig.json

This pull request includes several changes to improve error handling, add source maps for debugging, and update test prompts. The most important changes include adding source maps to various configuration files, enhancing error messages in the `vlmPlanning` function, and updating test case prompts for clarity.
Enhancements to error handling:
* [`packages/midscene/src/ai-model/ui-tars-planning.ts`](diffhunk://#diff-ff254e681ddc0cff307c6b78c4b95d6b7459131e4eeaa65c34474fdfbebcec37L136-R136): Enhanced the error message in the `vlmPlanning` function to include the reason from `res.content`.
Debugging improvements:
* [`packages/midscene/modern.config.ts`](diffhunk://#diff-687cd3f2fafbaac0311e92130861c026b65b7f3ef557e8f1c7e63058b87aa62aR23): Added `sourceMap: true` to the configuration to enable …

workflow: enhance error messages and improve the debugging experience.

---

packages/web-integration/src/playwright/reporter/index.ts

Added `playwright_test_id` to the test data attributes to improve traceability of test results. This change enhances reporting by uniquely identifying each test case, making it easier to analyze test execution and failures.

feat(reporting): Add test ID to test data attributes

---

README.md
README.zh.md

Add some links to badges: <a href="https://www.npmjs.com/package/@midscene/web"><img src="https://img.shields.io/npm/v/@midscene/web?style=flat-square&color=00a8f0" alt="npm version" /></a> <a href="https://npm-compare.com/@midscene/web/#timeRange=THREE_YEARS"><img src="https://img.shields.io/npm/dm/@midscene/web.svg?style=flat-square&color=00a8f0" alt="downloads" /></a>
The second badge makes users can view the dynamic download trends of [midscene](https://npm-compare.com/@midscene/web/#timeRange=THREE_YEARS). This let new users to easily see the `midscene` is getting more popularity.

doc: badge links

---

scripts/release.js

Potential fix for [https://github.com/web-infra-dev/midscene/security/code-scanning/14](https://github.com/web-infra-dev/midscene/security/code-scanning/14)
To fix the problem, we should avoid logging the entire error message directly, as it may contain sensitive information. Instead, we can log a generic error message and include only non-sensitive details. This approach ensures that sensitive data is not exposed in the logs while still providing useful information for debugging.
We will modify the code on line 102 to log a generic error message without including the potentially sensitive `error.message`. Additionally, we will ensure that any sensitive information from environment variables is not logged.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 14: Clear-text logging of sensitive information

---

apps/site/docs/en/automate-with-scripts-in-yaml.mdx
apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
packages/core/src/yaml.ts
packages/web-integration/src/puppeteer/agent-launcher.ts

feat(yaml): allow insecure https in yaml

---

packages/cli/src/yaml-runner.ts
packages/web-integration/modern.config.ts
packages/web-integration/package.json
packages/web-integration/src/puppeteer/index.ts

do not export puppeteer launcher since it requires puppeteer module

fix(puppeteer): optimize puppeteer export

---

package.json
packages/android-playground/src/scrcpy-server.ts
patches/@yume-chan__async.patch
pnpm-lock.yaml

ref: https://github.com/yume-chan/async/pull/44)

fix: compatible with node 20

---

packages/web-integration/src/bridge-mode/io-client.ts
packages/web-integration/src/bridge-mode/io-server.ts
packages/web-integration/tests/unit-test/bridge/io.test.ts

refactor(bridge): enhance error handling and connection logic in Bridge mode

---

packages/mcp/src/index.ts
packages/mcp/src/midscene.ts
packages/web-integration/src/bridge-mode/io-server.ts

fix(mcp): resolve MCP Bridge server connection timeout, then shut down MCP server

---

packages/mcp/src/index.ts
packages/mcp/src/midscene.ts
packages/web-integration/package.json
packages/web-integration/src/bridge-mode/agent-cli-side.ts
packages/web-integration/src/bridge-mode/io-server.ts
pnpm-lock.yaml

fix(mcp): resolve mcp bridge server connect timeout

---

packages/mcp/package.json
packages/mcp/src/midscene.ts
packages/web-integration/package.json
packages/web-integration/src/bridge-mode/agent-cli-side.ts
packages/web-integration/src/bridge-mode/index.ts
packages/web-integration/src/bridge-mode/io-server.ts
pnpm-lock.yaml

Reverts web-infra-dev/midscene#671

feat(mcp): make mcp navigated faster

---

packages/android/src/page/index.ts

Fix the issue where the custom ADB path does not take effect

feat(android): fix custom adb path no effect

---

apps/site/docs/en/integrate-with-playwright.mdx
apps/site/docs/zh/integrate-with-playwright.mdx

fix(site): update playwright example docs.

---

packages/core/src/ai-model/prompt/llm-planning.ts
packages/core/src/index.ts
packages/core/src/types.ts
packages/core/src/yaml.ts
packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
packages/core/tests/unit-test/types-rightclick.test.ts
packages/web-integration/src/chrome-extension/page.ts
packages/web-integration/src/common/agent.ts
packages/web-integration/src/common/plan-builder.ts
packages/web-integration/src/common/tasks.ts
packages/web-integration/src/common/ui-utils.ts
packages/web-integration/src/playwright/ai-fixture.ts
packages/web-integration/src/yaml/player.ts
packages/web-integration/tests/unit-test/__snapshots__/plan-builder.test.ts.snap
packages/web-integration/tests/unit-test/agent-rightclick.test.ts
packages/web-integration/tests/unit-test/page-task-executor-rightclick.test.ts
packages/web-integration/tests/unit-test/plan-builder.test.ts
packages/web-integration/tests/unit-test/yaml/__snapshots__/utils.test.ts.snap
packages/web-integration/tests/unit-test/yaml/player-rightclick.test.ts
packages/web-integration/tests/unit-test/yaml/utils.test.ts

* feat(core,web-integration): support right click (solve #558)
* feat(web-integration): add aiRightClick action to PlaywrightAiFixture

feat(core,web-integration): support right-click action (#762)

---

apps/site/docs/en/API.mdx
apps/site/docs/en/integrate-with-android.mdx
apps/site/docs/zh/API.mdx
apps/site/docs/zh/integrate-with-android.mdx
packages/android/src/agent/index.ts
packages/android/src/page/index.ts
packages/core/src/types.ts
packages/web-integration/src/chrome-extension/cdpInput.ts
packages/web-integration/src/common/agent.ts
packages/web-integration/src/common/page.d.ts
packages/web-integration/src/common/tasks.ts
packages/web-integration/src/index.ts
packages/web-integration/src/puppeteer/index.ts
packages/web-integration/src/puppeteer/page.ts

- aiInput supports autoDismissKeyboard parameter
- agent adds a parameter to control the default input behavior
- the default is to close after the input is completed.

support android auto hide keyborad for aiInput

---

apps/report/src/App.tsx
packages/visualizer/src/component/player.tsx

feat(visualizer): support download video for player

---

packages/web-integration/src/common/agent.ts
packages/web-integration/src/playwright/ai-fixture.ts

feat(agent): add onDumpUpdate callback and refactor afterTaskRunning to await its execution

---

.vscode/settings.json
apps/site/docs/en/API.mdx
apps/site/docs/en/model-provider.mdx
apps/site/docs/zh/API.mdx
apps/site/docs/zh/model-provider.mdx
packages/cli/package.json
packages/cli/src/cli-utils.ts
packages/cli/src/index.ts
packages/core/src/ai-model/service-caller/index.ts
packages/shared/src/env.ts
packages/web-integration/src/common/tasks.ts
pnpm-lock.yaml

1. allow configuring max recycle limits
2. add some doc for proxy

feat(core): allow configuring max recycle limits

---

packages/web-integration/src/yaml/player.ts

fix(web-intergration): fix typo

---

.prettierignore
README.md
README.zh.md
apps/site/docs/en/index.mdx
apps/site/docs/zh/index.mdx

fix(docs): fix mcp link

---

packages/evaluation/package.json
packages/mcp/package.json
packages/shared/package.json
pnpm-lock.yaml

chore(shared): unlock sharp version
